sudo: false
language: scala
scala:
  - 2.11.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - nutscracker@gmail.com
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)